com:
  alexmegremis:
    datasource:
      mariadb:
        url: jdbc:mariadb://NAS01.local:3307/spring_test
        username: spring_test
        password: ENC{UgKuC2Pb3XLLEQFUVMTC7w==}
        driver-class-name: org.mariadb.jdbc.Driver
      othermariadb:
        url: jdbc:mariadb://NAS01.local:3307/spring_test02
        username: spring_test02
        password: ENC{UgKuC2Pb3XLLEQFUVMTC7w==}
        driver-class-name: org.mariadb.jdbc.Driver

stuffToIgnore:
  aBoolean: true
  aString: Alex
  aNumber: 55
spring:
  application:
    admin:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    health:
      show-components: always
      show-details: always
    env:
      keys-to-sanitize:
