com:
  alexmegremis:
    datasource:
      mariadb:
        url: jdbc:mariadb://NAS01.local:3307/spring_test
        username:
        password:
        driver-class-name: org.mariadb.jdbc.Driver
      othermariadb:
        url: jdbc:mariadb://NAS01.local:3307/spring_test02
        username:
        password:
        driver-class-name: org.mariadb.jdbc.Driver

stuffToIgnore:
  aBoolean: true
  aString: Alex
  aNumber: 55
spring:
  application:
    admin:
      enabled: true
  ldap:
    urls: ldap://nas01.local:389
    base: dc=nas01,dc=local
    username:
    password:
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    health:
      show-components: always
      show-details: always
    env:
      keys-to-sanitize: