spring:
  datasource:
    url: jdbc:mariadb://NAS01.local:3307/spring_test
    data-username: spring_test
    password: ###Welcome123!foobar###

test:
  datasource:
    db01:
      username: root
      password: ###Welcome1!###
      url:
    db02:
      username: root
      password: ###09awuvwvmuwap94utan904wuva9tu4097t340987t3TC#$%V@#%G@#$5gh2345G@V%$GV###
      url:
    db03:
      username: root
      password: ###This-is-A-p@ssw0Rd###
      url:

stuffToIgnore:
  aBoolean: true
  aString: Alex
  aNumber: 55